# Generated by Django 4.2.1 on 2023-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMachineryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery_name', models.CharField(max_length=50)),
                ('machinery_function', models.CharField(max_length=100)),
                ('machinery_image', models.ImageField(upload_to='machineryimage')),
            ],
        ),
        migrations.CreateModel(
            name='CreatePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_firstname', models.CharField(default='', max_length=50)),
                ('trainee_lastname', models.CharField(default='', max_length=20)),
                ('trainee_username', models.CharField(default='', max_length=20)),
                ('trainee_mail', models.CharField(default='', max_length=50)),
                ('trainne_password', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CreatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_description', models.TextField()),
                ('plan_validity', models.CharField(max_length=100)),
                ('plan_amount', models.BigIntegerField()),
                ('workout_type', models.CharField(max_length=50)),
                ('days_per_week', models.CharField(max_length=25)),
                ('time_per_workout', models.CharField(max_length=25)),
                ('equipment_required', models.CharField(max_length=50)),
                ('target_gender', models.CharField(max_length=7)),
            ],
        ),
    ]
