# Generated by Django 4.2.1 on 2023-06-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_description', models.TextField()),
                ('plan_validity', models.CharField(max_length=100)),
                ('plan_amount', models.BigIntegerField()),
            ],
        ),
    ]
