# Generated by Django 4.2.1 on 2023-08-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatePassword',
            new_name='TraineeRegister',
        ),
    ]
