# Generated by Django 4.2.1 on 2023-08-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0002_rename_createpassword_traineeregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeregister',
            name='trainee_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='traineeregister',
            name='trainee_gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='traineeregister',
            name='trainee_number',
            field=models.BigIntegerField(default=11),
            preserve_default=False,
        ),
    ]
