# Generated by Django 4.2.1 on 2023-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0002_workoutsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='createplan',
            name='days_per_week',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createplan',
            name='equipment_required',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createplan',
            name='target_gender',
            field=models.CharField(default=6, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createplan',
            name='time_per_workout',
            field=models.CharField(default=7, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createplan',
            name='workout_type',
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkoutSummary',
        ),
    ]
