# Generated by Django 4.2.1 on 2023-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_admin', '0003_createplan_days_per_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_firstname', models.CharField(default='', max_length=50)),
                ('trainee_lastname', models.CharField(default='', max_length=20)),
                ('trainee_username', models.CharField(default='', max_length=20)),
                ('trainee_mail', models.CharField(default='', max_length=50)),
                ('trainne_password', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
