# Generated by Django 4.2.1 on 2023-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_fname', models.CharField(max_length=100)),
                ('register_lname', models.CharField(max_length=100)),
                ('register_username', models.CharField(max_length=100)),
                ('register_email', models.CharField(max_length=100)),
                ('register_password', models.CharField(max_length=8)),
                ('user_type', models.CharField(max_length=100)),
                ('register_address', models.TextField()),
                ('register_pin', models.BigIntegerField()),
                ('register_state', models.CharField(max_length=100)),
                ('register_city', models.CharField(max_length=100)),
                ('register_gender', models.CharField(max_length=20)),
                ('register_dob', models.DateField()),
                ('register_phone', models.BigIntegerField()),
                ('register_selectplan', models.CharField(max_length=100)),
                ('blood_group', models.CharField(default='', max_length=20)),
                ('user_height', models.CharField(default='', max_length=25)),
                ('user_weight', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
