# Generated by Django 4.2.1 on 2023-07-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_photo',
            field=models.ImageField(default='', upload_to='userphoto'),
        ),
    ]
