# Generated by Django 4.2.1 on 2023-08-04 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_register_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
