# Generated by Django 4.2.1 on 2023-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_loginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
    ]
