# Generated by Django 4.2.1 on 2023-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_register_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='attendance',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
