# Generated by Django 4.2.1 on 2023-06-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_delete_loginuser_register_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='register_selectplan',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
