# Generated by Django 4.2.1 on 2023-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_register_register_selectplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='blood_group',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='user_height',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='register',
            name='user_weight',
            field=models.CharField(default='', max_length=25),
        ),
    ]
