# Generated by Django 4.2.1 on 2023-07-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        ('gym_trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthstatus',
            name='user_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.register'),
            preserve_default=False,
        ),
    ]
