# Generated by Django 4.2.1 on 2023-07-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_trainee', '0003_userattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='attendance',
            field=models.CharField(default='absent', max_length=10),
        ),
    ]
