# Generated by Django 4.2.1 on 2023-08-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_trainee', '0004_alter_userattendance_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraineeRegister',
        ),
    ]
