# Generated by Django 4.2.1 on 2023-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_trainee', '0005_delete_traineeregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise_type', models.CharField(default='', max_length=50)),
                ('day_1', models.CharField(default='', max_length=50)),
                ('day_2', models.CharField(default='', max_length=50)),
                ('day_3', models.CharField(default='', max_length=50)),
                ('day_4', models.CharField(default='', max_length=50)),
                ('day_5', models.CharField(default='', max_length=50)),
                ('day_6', models.CharField(default='', max_length=50)),
                ('day_7', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
