# Generated by Django 4.2.1 on 2023-08-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_register_user_photo'),
        ('gym_trainee', '0006_uploadroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='user_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.register'),
            preserve_default=False,
        ),
    ]
