# Generated by Django 4.2.1 on 2023-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_trainee', '0007_userattendance_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_to_add', models.JSONField(blank=True, default=list)),
                ('food_to_avoid', models.JSONField(blank=True, default=list)),
                ('pre_workout_food', models.JSONField(blank=True, default=list)),
                ('post_workout_food', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'fitnessdietplan',
            },
        ),
    ]
