# Generated by Django 4.2.1 on 2023-08-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_register_time_stamp'),
        ('gym_trainee', '0008_fitnessdietplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdietplan',
            name='user_fk',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='fitness.register'),
            preserve_default=False,
        ),
    ]
