# Generated by Django 4.2.1 on 2023-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_trainee', '0009_fitnessdietplan_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='attendance_status',
            field=models.BooleanField(default=False),
        ),
    ]
