# Generated by Django 4.2.1 on 2023-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_trainee', '0010_userattendance_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattendance',
            name='attendance_status',
        ),
    ]
